# Generated by Django 5.1.2 on 2024-11-01 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitmodel',
            options={'verbose_name': 'Debit', 'verbose_name_plural': 'Debits'},
        ),
        migrations.AddField(
            model_name='debitmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
